layout_spectrum: 0.4665029
typography_spectrum: 0.9949589
color:
  saturation: 0.4526992
  lightness: 0.8038027
  brandStrength: 0.9904645
  rhythmicContrast: 0.4321388
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: NC MOVE
